quiz/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home.as_view()),
    path('quiz/handle_response', views.HandleResponse.as_view()),
    path('quiz/<str:slug>', views.QuizDetail.as_view(), name='quiz-detail'),
    path('quiz/<str:slug>/questions', views.Questions.as_view()),
    path('quiz/<str:slug>/<int:id>', views.ShowAnswer.as_view()),

]

quizapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quiz.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/models.py
from django.db import models
from django.template.defaultfilters import slugify

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=200)
    thumbnail=models.ImageField(blank=True)

    def __str__(self):
        return self.name

class Quiz(models.Model):
    title=models.CharField(max_length=200)
    subtext=models.TextField()
    thumbnail=models.ImageField()
    author=models.CharField(max_length=200)
    category=models.ForeignKey(Category, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug=slugify(self.title)
        super(Quiz, self).save(*args, **kwargs)




class Question(models.Model):
    type=models.CharField(max_length=200, choices=(('Text', 'Text'), ('Image', 'Image')))
    text=models.TextField()
    no=models.IntegerField()
    thumbnail=models.ImageField(null=True, blank=True)
    quiz=models.ForeignKey(Quiz, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

class Option(models.Model):
    img_option=models.ImageField(null=True, blank=True)
    text_option=models.TextField(null=True, blank=True)
    weight = models.CharField(max_length=200)
    question=models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return '-> '+self.text_option + ' for '+self.question.text

class Answers(models.Model):
    min_score=models.IntegerField()
    max_score=models.IntegerField()
    name=models.TextField()
    thumbnail=models.ImageField()
    quiz=models.ForeignKey(Quiz, on_delete=models.CASCADE)
    description=models.TextField(null=True)

    def __str__(self):
        return self.name

quiz/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView
from django.views import View
from .models import Quiz, Question, Answers
from django.http import JsonResponse

# Create your views here.

class Home(ListView):
    model=Quiz
    queryset = Quiz.objects.all()
    context_object_name = 'quizs'
    template_name = 'index.html'

class NextQuizsMixin:

    def get_context_data(self, **kwargs):
        context=super(NextQuizsMixin, self).get_context_data(**kwargs)
        context['next_quizs']=Quiz.objects.all()[0:5]
        return context

class QuizDetail(NextQuizsMixin, DetailView):
    model=Quiz
    context_object_name = 'quiz'
    template_name = 'quiz.html'
    slug_field = 'slug'



class Questions(NextQuizsMixin,DetailView):
    model = Quiz
    context_object_name ='quiz'
    template_name = 'question.html'
    slug_field = 'slug'

    def get_context_data(self, **kwargs):
        context=super(Questions, self).get_context_data(**kwargs)
        context['questions']=Question.objects.filter(quiz=self.object)
        context['no_of_questions']=context['questions'].__len__()
        return context

class HandleResponse(View):

    def get(self,request, *args, **kwargs):
        score=request.GET.get('score')
        quiz_id=request.GET.get('quiz_id')
        answers=Answers.objects.filter(quiz_id=quiz_id)
        quiz=Quiz.objects.get(id=quiz_id)
        for answer in answers:
            if answer.min_score <= int(score) and answer.max_score >= int(score) :
                result= answer
        return JsonResponse({'answer_id':result.id, 'quiz_id':quiz_id, 'quiz_slug':quiz.slug})


class ShowAnswer(NextQuizsMixin,DetailView):
    model = Answers
    template_name = 'answer.html'
    context_object_name = 'answer'
    pk_url_kwarg = 'id'

    def get_context_data(self, **kwargs):
        context=super(ShowAnswer, self).get_context_data(**kwargs)
        context['quiz']=self.object.quiz
        return context

quiz/templates/answer.html
{%  extends 'base.html' %}
{%  block content %}
<main>
	<div class="container thumblist-container">
		<div class="row">
			<div class="col-xs-12" style="margin-bottom: 40px;">
				<img src="/static/ad.png" class="img-responsive" style="margin-left: auto;margin-right: auto">
			</div>
		</div>
		<div class="row">
			<div class="col-md-8">
				<img src="{{ answer.thumbnail.url }}" class="img-responsive" style="width:100%;margin-bottom: 20px;">
                <h3 class="title">{{ answer.name}}</h3>
                <p>{{ answer.description }}</p>
				<div class="sharethis-inline-share-buttons"></div>
                <div class="spacer10"></div>
                 <div class="spacer10"></div>



                <div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

var disqus_config = function () {
this.page.url = 'http://tolucareer.pythonanywhere.com/quiz/{{ quiz.slug }}';  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = '{{ quiz.slug }}'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://olayemi.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>


                			     <div class="spacer10"></div>
                 <div class="spacer10"></div>
                 <div class="spacer10"></div>
            </div>
			{%  include 'includes/sidebar.html' %}
		</div>

	</div>
	</main>
{%  endblock %}
{%  block links %}
    <script type='text/javascript' src="https://platform-api.sharethis.com/js/sharethis.js#property=5c34ea2cede3ff00103ac16f&product='inline-share-buttons'" async='async'></script>
    <meta property="og:site_name" content="Olayemi" />
    <meta property="og:type" content="article" />
    <meta property="og:url" content="/quiz/{{ quiz.slug }}" />
    <meta property="og:title" content="{{ answer.quiz.title }}" />
    <meta property="og:description" content="{{ answer.name }}" />
    <meta property="og:image" content="{{ answer.thumbnail.url }}" />
{% endblock %}

quiz/templates/base.html
<html>
	<head>
	    <meta charset="utf-8" />
	    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=0">
	    <meta name="copyright" content="Copyright Swyfft LLC 2018" />
	    <meta name="description" content="Quiz App" />

	    <title>Quiz App</title>
	    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" typpe="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
	    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
	    <link href="/static/style.css" rel="stylesheet">
     <!--Google Fonts-->
    <link href="https://fonts.googleapis.com/css?family=Comfortaa:300,400,500,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
        {%  block links %}{%  endblock %}
    </head>
	<body>
    <div id="fb-root"></div>
		<script>(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.2&appId=707728196083985&autoLogAppEvents=1';
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script>
		<nav class="navbar navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Olayemi</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <!--ul class="nav navbar-nav">
        <li class=""><a href="#">Music<span class="sr-only">(current)</span></a></li>
        <li class=""><a href="#">Movie<span class="sr-only">(current)</span></a></li>
        <li class=""><a href="#">Art<span class="sr-only">(current)</span></a></li>

      </ul-->


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
{%  block content %}{%  endblock  %}
<script
  			src="https://code.jquery.com/jquery-3.3.1.min.js"
  			integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  			crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js"></script>
        <script src="https://cdn.datatables.net/plug-ins/1.10.19/sorting/datetime-moment.js"></script>
    {%  block scripts %}{%  endblock %}
	</body>
</html>

quiz/templates/includes/sidebar.html
            <div class="col-md-4">
				<div class="row">
					<a href="https://rhbooks.com.ng/product/women-of-the-ayo-kessington-dynasty-volume-1-anjolas-diary/"><img class="ad2 img-responsive" src="/static/book_ad.png"></a>
                <!-- just checking -->
				</div>
								<div class="spacer10"></div>
				{%  for quiz in next_quizs %}
                    <div class="row thumblist small">
                        <div class="col-xs-4 thumblist-img" style="background-image: url({{ quiz.thumbnail.url }})">

                        </div>
                        <div class="col-xs-8">
                            <h4>{{ quiz.title }}</h4>
                        </div>
                    </div>
                {%  endfor %}
			</div>

quiz/templates/index.html
{%  extends 'base.html' %}
{% block content %}
<main>
	<div class="container thumblist-container">
		<div class="row">
			<div class="col-xs-12" style="margin-bottom: 40px;">
                <a href="https://rhbooks.com.ng/product/women-of-the-ayo-kessington-dynasty-volume-1-anjolas-diary/"><img src="/static/ad.png" class="img-responsive" style="margin-left: auto;margin-right: auto"></a>
			</div>
		</div>
		<div class="row">
			<div class="col-md-8">
                {%  for quiz in quizs %}
				<div class="row thumblist">
					<div class="col-xs-4 thumblist-img" style="background-image: url({{ quiz.thumbnail.url }})">

					</div>
					<div class="col-xs-8">
                        <a href="/quiz/{{ quiz.slug }}" style="color:#000"><h4>{{ quiz.title }}</h4></a>
						<p>{{ quiz.subtext }}</p>
					</div>
				</div>
                {%  endfor %}
			</div>
			<div class="col-md-4">
				<div class="row">
                    <a href="https://rhbooks.com.ng/product/women-of-the-ayo-kessington-dynasty-volume-1-anjolas-diary/"><img class="ad2 img-responsive"  src="/static/book_ad.png"></a>

				</div>
			</div>
		</div>
	</div>
	</main>
{%  endblock %}

quiz/templates/question.html
{%  extends 'base.html' %}
{%  block content %}
<main>
	<div class="container thumblist-container">
		<div class="row">
			<div class="col-xs-12" style="margin-bottom: 40px;">
				<img src="/static/ad.png" class="img-responsive" style="margin-left: auto;margin-right: auto">
			</div>
		</div>
		<div class="row">
			<div class="col-md-8 ">
                <p style="font-size: 30px; margin:0 0 0px"><span id="where">1</span> of {{ no_of_questions }}</p>
				<hr style="margin-top: 0px">
				<div class="content text-center">
                    {%  for question in questions %}
						<h3>{{ question.text }}</h3>
                        <div class="spacer10"></div>
                        <div class="spacer10"></div>
                        {%  for option in question.option_set.all %}
                            <a class="options btn btn-primary" data-weight="{{ option.weight }}" question_no="{{ question.no }}">{{ option.text_option }}</a>
                            <div class="spacer10"></div>
                         {%  endfor %}
                    {%  endfor %}
				</div>

					</div>
        <div class="sidebar"></div>
			{%  include 'includes/sidebar.html' %}
        </div>
		</div>
	</div>
	</main>
{%  endblock %}
{%  block scripts %}
    <script>
        questions=[
            {%  for question in questions %}
            {
                    'text':'{{ question.text }}',
                    'no':{{ question.no }},
                    'options':[
                        {%  for option in question.option_set.all %}
                        {
                            'text':'{{ option.text_option }}',
                            'weight':'{{ option.weight }}',
                        },
                            {% endfor %}
                    ]
                    }
                ,
            {% endfor %}

        ];
        sessionStorage.setItem('score',parseInt(0))
        $('.content').on('click', '.options',function(e){
            e.preventDefault();
            score=parseInt(sessionStorage.getItem('score'))+parseInt($(this).attr('data-weight'))
            sessionStorage.setItem('score', score);
            question_what=$(this).attr('question_no');
            next_or_submit(question_what);
        });

    function next_or_submit(question_no){
            no_of_questions={{ no_of_questions }}
            if (question_no == no_of_questions){
                //meaning last question , therefore submit data and process
                $.get('/quiz/handle_response', {'quiz_id':{{quiz.id}}, 'score':parseInt(sessionStorage.getItem('score'))} )
                    .done(function (data) {
                        //alert(data.answer_id)
                        window.location='/quiz/'+data.quiz_slug+'/'+data.answer_id
                    })
            }else{
                question=questions[question_no]
                console.log(question_no)
                fill_content(question)
            }
    }

    function fill_content(question){
                question_string="<h3>"+question.text+"</h3> <div class'spacer10'></div> <div class='spacer10'></div>";
                options=question.options;
                options_string='';
                options.forEach(function(option){
                     options_string+="<a class='options btn btn-primary' data-weight='"+option.weight+"' question_no='"+question.no+"' >"+option.text+"</a> <div class='spacer10'></div>"
                });
                next_question=question_string+options_string;
                $('.content').html(next_question);
                $('#where').text(question.no);
    }

    question=questions[0]
    fill_content(question)

    </script>
{%  endblock %}

{% block links %}
    <meta property="og:site_name" content="Olayemi" />
    <meta property="og:type" content="article" />
    <meta property="og:url" content="/quiz/{{ quiz.slug }}" />
    <meta property="og:title" content="{{ quiz.text }}" />
    <meta property="og:description" content="{{ quiz.subtext }}" />
    <meta property="og:image" content="{{ quiz.subtext }}" />
{%  endblock %}

quiz/templates/quiz.html
{%  extends 'base.html' %}
{%  block content %}
<main>
	<div class="container thumblist-container">
		<div class="row">
			<div class="col-xs-12" style="margin-bottom: 40px;">
				<img src="/static/ad.png" class="img-responsive" style="margin-left: auto;margin-right: auto">
			</div>
		</div>
		<div class="row">
			<div class="col-md-8 text-center">
				<h3 class="title">{{ quiz.title }}</h3>
				<img src="{{ quiz.thumbnail.url }}" class="img-responsive" style="width:100%;margin-bottom: 20px;">
				<a class="btn btn-primary start" href="/quiz/{{ quiz.slug }}/questions">Start Now</a>

				<div class="sharethis-inline-share-buttons"></div>
                <div class="spacer10"></div>
                 <div class="spacer10"></div>
                <div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

var disqus_config = function () {
this.page.url = 'http://tolucareer.pythonanywhere.com/quiz/{{ quiz.slug }}';  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = '{{ quiz.slug }}'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://olayemi.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                            			     <div class="spacer10"></div>
                 <div class="spacer10"></div>
                 <div class="spacer10"></div>
            </div>
			{%  include 'includes/sidebar.html' %}
		</div>

	</div>
	</main>
{%  endblock %}
{%  block links %}
    <script type='text/javascript' src="https://platform-api.sharethis.com/js/sharethis.js#property=5c34ea2cede3ff00103ac16f&product='inline-share-buttons'" async='async'></script>
     <meta property="og:site_name" content="Olayemi" />
    <meta property="og:type" content="article" />
    <meta property="og:url" content="/quiz/{{ quiz.slug }}" />
    <meta property="og:title" content="{{ quiz.text }}" />
    <meta property="og:description" content="{{ quiz.subtext }}" />
    <meta property="og:image" content="{{ answer.thumbnail.url }}" />
{%  endblock %}